# Generated by Django 5.0.6 on 2024-07-09 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_privatechat_privatemessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='privatechat',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='privatechat',
            constraint=models.UniqueConstraint(condition=models.Q(('user1__lt', models.F('user2')), ('user1__gt', models.F('user2')), _connector='OR'), fields=('user1', 'user2'), name='unique_private_chat'),
        ),
    ]
